import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { qatarLocal, utcNow } from "@/lib/utils/time";

export interface AuditRow {
  action: string;
  resource_type: string | null;
  resource_id: string | null;
  user_id: string | null;
  occurred_at: string;
}

export interface AuditReportMeta {
  orgName: string;
  orgId: string;
  generatedBy: string;
}

/** Column layout (x offset in points, width, label). */
const COLS = [
  { x: 40, w: 120, label: "Action" },
  { x: 160, w: 110, label: "Resource" },
  { x: 270, w: 120, label: "Actor" },
  { x: 390, w: 165, label: "Time (Qatar)" },
];

const PAGE_W = 595.28; // A4 portrait
const PAGE_H = 841.89;
const MARGIN = 40;
const ROW_H = 16;

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

/**
 * Render an immutable audit trail to a PDF suitable for QFC compliance
 * reporting. Header carries org identity, generation time (UTC + Qatar), and
 * the operator; the body is a paginated table of events.
 */
export async function buildAuditPdf(meta: AuditReportMeta, rows: AuditRow[]): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = drawHeader(page, bold, font, meta);
  y = drawTableHead(page, bold);

  for (const row of rows) {
    if (y < MARGIN + ROW_H) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN;
      y = drawTableHead(page, bold, y);
    }
    const cells = [
      truncate(row.action, 24),
      truncate(row.resource_type ? `${row.resource_type} ${(row.resource_id ?? "").slice(0, 8)}` : "—", 22),
      truncate(row.user_id ?? "system/api", 24),
      qatarLocal(new Date(row.occurred_at)),
    ];
    cells.forEach((c, i) => {
      page.drawText(c, { x: COLS[i].x, y, size: 8, font, color: rgb(0.1, 0.12, 0.16) });
    });
    y -= ROW_H;
  }

  // Footer with total on the last page.
  page.drawText(`${rows.length} event(s) · retained 7 years per QFC requirements`, {
    x: MARGIN,
    y: MARGIN / 2,
    size: 7,
    font,
    color: rgb(0.5, 0.5, 0.55),
  });

  return doc.save();
}

function drawHeader(page: PDFPage, bold: PDFFont, font: PDFFont, meta: AuditReportMeta): number {
  const top = PAGE_H - MARGIN;
  page.drawText("FlowOrchestrator — Audit Trail Report", { x: MARGIN, y: top, size: 16, font: bold, color: rgb(0.06, 0.09, 0.16) });
  const lines = [
    `Organization: ${meta.orgName} (${meta.orgId})`,
    `Generated (UTC): ${utcNow()}`,
    `Generated (Qatar): ${qatarLocal()}`,
    `Generated by: ${meta.generatedBy}`,
  ];
  lines.forEach((l, i) => {
    page.drawText(l, { x: MARGIN, y: top - 22 - i * 13, size: 9, font, color: rgb(0.3, 0.33, 0.4) });
  });
  return top - 22 - lines.length * 13 - 10;
}

function drawTableHead(page: PDFPage, bold: PDFFont, atY?: number): number {
  const y = atY ?? PAGE_H - MARGIN - 90;
  COLS.forEach((c) => {
    page.drawText(c.label, { x: c.x, y, size: 9, font: bold, color: rgb(0.06, 0.09, 0.16) });
  });
  page.drawLine({
    start: { x: MARGIN, y: y - 4 },
    end: { x: PAGE_W - MARGIN, y: y - 4 },
    thickness: 0.5,
    color: rgb(0.8, 0.82, 0.85),
  });
  return y - 18;
}
